/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChatKeywordDrawer: typeof import('./components/chat/ChatKeywordDrawer.vue')['default']
    ChatMembersDrawer: typeof import('./components/chat/ChatMembersDrawer.vue')['default']
    ChatMessageDrawer: typeof import('./components/chat/ChatMessageDrawer.vue')['default']
    ChatRoomEditorDrawer: typeof import('./components/chat/ChatRoomEditorDrawer.vue')['default']
    CommentContextDrawer: typeof import('./components/moderation/CommentContextDrawer.vue')['default']
    DanmakuContextDrawer: typeof import('./components/danmaku/DanmakuContextDrawer.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTimeline: typeof import('element-plus/es')['ElTimeline']
    ElTimelineItem: typeof import('element-plus/es')['ElTimelineItem']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    FinanceEventDrawer: typeof import('./components/finance/FinanceEventDrawer.vue')['default']
    MetricCard: typeof import('./components/MetricCard.vue')['default']
    NovelEditorDrawer: typeof import('./components/ai-novels/NovelEditorDrawer.vue')['default']
    NovelReviewDrawer: typeof import('./components/ai-novels/NovelReviewDrawer.vue')['default']
    ReportDetailDrawer: typeof import('./components/moderation/ReportDetailDrawer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionCard: typeof import('./components/SectionCard.vue')['default']
    ShopItemDetailDrawer: typeof import('./components/shop/ShopItemDetailDrawer.vue')['default']
    ShopItemEditorDrawer: typeof import('./components/shop/ShopItemEditorDrawer.vue')['default']
    ShopStatusDialog: typeof import('./components/shop/ShopStatusDialog.vue')['default']
    UserBanDialog: typeof import('./components/users/UserBanDialog.vue')['default']
    UserDetailDrawer: typeof import('./components/users/UserDetailDrawer.vue')['default']
    UserEconomyDialog: typeof import('./components/users/UserEconomyDialog.vue')['default']
    UserProfileDialog: typeof import('./components/users/UserProfileDialog.vue')['default']
    UserUnbanDialog: typeof import('./components/users/UserUnbanDialog.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
